#+title: Todos

* CI and testing
** DONE move to node:test and node:assert
** DONE Move away from simon
** github actions workflow
* DONE Fix plurals handling
* CANCELLED Add sprintf-js integration

Being able to do

#+begin_src js
ngettext(
    `You provided %n positional argument.`,
    `You provided %n positional arguments.`,
    parsedArgs.positionals.length, // count
    parsedArgs.positionals.length, // format arg
),
#+end_src

+is not only nice to have, it is necessary.+

2025-12-28T00:44:38+0900: Actually, no, even upstream gettext is used like =printf(_("format string %s"), arg)=, the gettext call itself doesn't embed the sprintf formatting.

* Getting locale; locale fallback logic; reading locale from environment

- We should read LANGUAGE, LC_ALL, LC_MESSAGES, LANG in that order (except if LANG is C then always return msgid)
- We need a way to specify the current locale per request. This probably means splitting catalog from the gettext instance.

* “multithreaded” locale

We need to check what bindtextdomain does. Also is there a bindlocale in the C/++ library?

Make a function that takes a locale and returns each localization function, like

#+begin_src javascript
const { _, ngettext } = gt.bindLocale("pt_BR")
#+end_src

then these returned functions can effectively have the locale as their own state, instead of relying on state in the class. This should eliminate the need to have more than one instance of the Gettext class, even for server applications.

The main object should load the catalog (either from options or from reading files), then there should be a function for returning functions that have bound to a given locale.

* Example project / sandboxes for Astro, SvelteKit
* Extraction command

Extract from ts/js/tsx/jsx, as well as Astro or Svelte (or others) as long as their compile-to-JS packages are installed, as well as support supplying custom functions.

* examples(astro)
** specify language via astro:i18n
