#+title: Todos

* CI and testing
** DONE move to node:test and node:assert
** Move away from simon
** github actions workflow
* Fix plurals handling
* fix prototype pollution

cf. https://github.com/postalsys/gettext/commit/63e627cece1592d03abadf36044c957b801c7315

I want to take the approach of using Maps instead though.

* CANCELLED Add sprintf-js integration

Being able to do

#+begin_src js
ngettext(
    `You provided %n positional argument.`,
    `You provided %n positional arguments.`,
    parsedArgs.positionals.length, // count
    parsedArgs.positionals.length, // format arg
),
#+end_src

+is not only nice to have, it is necessary.+

2025-12-28T00:44:38+0900: Actually, no, even upstream gettext is used like =printf(_("format string %s"), arg)=, the gettext call itself doesn't embed the sprintf formatting.

* Getting locale; locale fallback logic; reading locale from environment

- We should read LANGUAGE, LC_ALL, LC_MESSAGES, LANG in that order (except if LANG is C then always return msgid)
- We need a way to specify the current locale per request. This probably means splitting catalog from the gettext instance.
