#+title: Todos

* CI and testing
** DONE move to node:test and node:assert
** DONE Move away from simon
** github actions workflow
* DONE Fix plurals handling
* CANCELLED Add sprintf-js integration

Being able to do

#+begin_src js
ngettext(
    `You provided %n positional argument.`,
    `You provided %n positional arguments.`,
    parsedArgs.positionals.length, // count
    parsedArgs.positionals.length, // format arg
),
#+end_src

+is not only nice to have, it is necessary.+

2025-12-28T00:44:38+0900: Actually, no, even upstream gettext is used like =printf(_("format string %s"), arg)=, the gettext call itself doesn't embed the sprintf formatting.

* Option to read catalogs from directory
:PROPERTIES:
:created:  2025-12-30T06:40:11+0900
:END:

Sure we can do it from the consumer's side, and sure we want the flexibility to load translations however we want, but it's also nice to be able to just specify a path and get everything loaded that way.

This is kind of what bindtextdomain does. But because we want to load translations from the project instead of from the system wide message catalog location, it makes sense to deviate from bindtextdomain.

* Getting locale; locale fallback logic; reading locale from environment

- We should read LANGUAGE, LC_ALL, LC_MESSAGES, LANG in that order (except if LANG is C then always return msgid)
- We need a way to specify the current locale per request. This probably means splitting catalog from the gettext instance.

* Per-string fallbacks
* Example project / sandboxes for SvelteKit
* Extraction command

Extract from ts/js/tsx/jsx, as well as Astro or Svelte (or others) as long as their compile-to-JS packages are installed, as well as support supplying custom functions.

* TODO examples(SPA, gettext runtime on client side)
* TODO examples(sveltekit)
* examples(astro)
** specify language via astro:i18n
** static mode: i18n pages
** server mode: auto redirect i18n
** how should components get the context?
Pages would need to somehow pass the context into components, either manually or with some state manager. Then each component can do bindLocale to get their own references to the translator functions with the right context. It's either that or passing the functions themselves, which also sounds messy.

bindLocale seriously needs to not completely reinitialize the functions.
