name: Publish rollup-plugin-gettext
on:
  push:
    tags:
      - "rollup-plugin-gettext-*"

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
      - uses: actions/checkout@v6
      - uses: pnpm/action-setup@v6
        with:
          version: 11
      - uses: actions/setup-node@v6
        with:
          node-version: 26
          cache: "pnpm"
      - name: Install packages
        run: |
          sudo apt-get install gettext
          cd packages/rollup-plugin-gettext
          pnpm install
      - name: Build
        run: |
          cd packages/rollup-plugin-gettext
          make build
      - name: Test
        run: |
          cd packages/rollup-plugin-gettext
          make test
      - name: Publish
        run: |
          cd packages/rollup-plugin-gettext
          make publish
