name: Test rollup-plugin-gettext
on:
  push:
    paths:
      - "packages/rollup-plugin-gettext/**"
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: pnpm/action-setup@v4
        with:
          version: 11
      - uses: actions/setup-node@v6
        with:
          node-version: 24
          cache: "pnpm"
      - name: Install packages
        run: |
          sudo apt-get install gettext
          cd packages/rollup-plugin-gettext
          pnpm install
      - name: Build
        run: |
          cd packages/rollup-plugin-gettext
          make build
      - name: Test
        run: |
          cd packages/rollup-plugin-gettext
          make test
